In [2]:
import numpy as np
import pandas as pd
data  = np.arange(-20, 20, 3)
data

array([-20, -17, -14, -11,  -8,  -5,  -2,   1,   4,   7,  10,  13,  16,
        19])

## 最小-最大规范化

In [3]:
a = map(lambda x: (x - data.min()) / (data.max() - data.min()), data)
a = list(a)
a

[0.0,
 0.07692307692307693,
 0.15384615384615385,
 0.23076923076923078,
 0.3076923076923077,
 0.38461538461538464,
 0.46153846153846156,
 0.5384615384615384,
 0.6153846153846154,
 0.6923076923076923,
 0.7692307692307693,
 0.8461538461538461,
 0.9230769230769231,
 1.0]

In [4]:
(data - data.min()) / (data.max() - data.min())

array([0.        , 0.07692308, 0.15384615, 0.23076923, 0.30769231,
       0.38461538, 0.46153846, 0.53846154, 0.61538462, 0.69230769,
       0.76923077, 0.84615385, 0.92307692, 1.        ])

## 零-均值规范化

In [5]:
a = map(lambda x: (x - data.mean()) / data.std(), data)
a = list(a)
a

[-1.61245154965971,
 -1.3643820804812932,
 -1.116312611302876,
 -0.8682431421244593,
 -0.6201736729460423,
 -0.3721042037676254,
 -0.12403473458920847,
 0.12403473458920847,
 0.3721042037676254,
 0.6201736729460423,
 0.8682431421244593,
 1.116312611302876,
 1.3643820804812932,
 1.61245154965971]

In [6]:
(data - data.mean()) / data.std()

array([-1.61245155, -1.36438208, -1.11631261, -0.86824314, -0.62017367,
       -0.3721042 , -0.12403473,  0.12403473,  0.3721042 ,  0.62017367,
        0.86824314,  1.11631261,  1.36438208,  1.61245155])

## 小数定标规范化

In [9]:
a = map(lambda x: x / (10 ** np.ceil(np.log10(max(abs(data))))), data)
a = list(a)
a

[-0.2,
 -0.17,
 -0.14,
 -0.11,
 -0.08,
 -0.05,
 -0.02,
 0.01,
 0.04,
 0.07,
 0.1,
 0.13,
 0.16,
 0.19]

In [7]:
data / 10 ** np.ceil(np.log10(max(abs(data))))

array([-0.2 , -0.17, -0.14, -0.11, -0.08, -0.05, -0.02,  0.01,  0.04,
        0.07,  0.1 ,  0.13,  0.16,  0.19])